@startuml MVVM Example

[*] -> Render : The webpage needs to be rendered
Render --> List_of_People_View
State_Management -> Render : Contains data for
List_of_People --> List_of_People_View : Passed to view component
List_of_People_View -> State_Management : Updates to list of people
List_of_People_View --> Table_View : Table view rows
Table_View -> List_of_People_View : Update to row operations
@enduml